sudo: false

services:
  - docker

before_script:
  - docker -v
  - docker build . -t $APP_IMAGE

script:
  - docker run $APP_IMAGE python3 -m pytest

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true

branches:
  only:
    - master
    - /\d+\.\d+\.\d+/
