version: '3'
services:
  # for development purposes
  dev:
    build: .
    image: "kbc-wr-zoho-crm:dev"
    volumes:
        - ./:/code
        - ./data:/data
    command:
      - /bin/sh
    env_file:
      - .env
